//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mAgIc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActions
    {
        public int IDIslem { get; set; }
        public int IDYapan { get; set; }
        public string yuklenenVideoPath { get; set; }
        public string tahminEdilenKategori { get; set; }
        public System.DateTime Zaman { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
